"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-23 15:56:56.165006
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('editorial_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_editorial_events_entity', 'editorial_events', ['entity_type', 'entity_id'], unique=False)
    op.create_table('email_otps',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_otps_email'), 'email_otps', ['email'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=32), server_default='listener', nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ui_language', sa.String(length=16), server_default='en', nullable=False),
    sa.Column('listening_languages', postgresql.ARRAY(sa.String(length=16)), server_default=sa.text("ARRAY['te-IN']::varchar[]"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('workers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('capabilities', postgresql.ARRAY(sa.String(length=32)), server_default='{}', nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('info', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('audio_assets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_key', sa.Text(), nullable=False),
    sa.Column('source_filename', sa.Text(), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('album', sa.Text(), nullable=True),
    sa.Column('collection', sa.Text(), nullable=True),
    sa.Column('artist', sa.Text(), nullable=True),
    sa.Column('narrator_name', sa.Text(), nullable=True),
    sa.Column('narrator_user_id', sa.BigInteger(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_required', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('track_number', sa.Text(), nullable=True),
    sa.Column('episode_number', sa.Text(), nullable=True),
    sa.Column('genre', sa.Text(), nullable=True),
    sa.Column('genres', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('language', sa.String(length=16), server_default='te-IN', nullable=False),
    sa.Column('year', sa.Text(), nullable=True),
    sa.Column('audience_age_range', sa.Text(), nullable=True),
    sa.Column('mood', sa.Text(), nullable=True),
    sa.Column('listening_contexts', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('content_warnings', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('keywords', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('moral_takeaway', sa.Text(), nullable=True),
    sa.Column('source_adaptation', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), server_default='0', nullable=False),
    sa.Column('bitrate', sa.Integer(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('channels', sa.Integer(), nullable=True),
    sa.Column('has_embedded_artwork', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='draft', nullable=False),
    sa.Column('metadata_review_status', sa.String(length=24), server_default='not-reviewed', nullable=False),
    sa.Column('parent_asset_id', sa.String(length=32), nullable=True),
    sa.Column('version_number', sa.Integer(), server_default='1', nullable=False),
    sa.Column('artwork_key', sa.Text(), nullable=True),
    sa.Column('artwork_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('renditions', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('media_status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('qc', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['narrator_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_asset_id'], ['audio_assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_key')
    )
    op.create_index(op.f('ix_audio_assets_collection'), 'audio_assets', ['collection'], unique=False)
    op.create_index(op.f('ix_audio_assets_language'), 'audio_assets', ['language'], unique=False)
    op.create_index(op.f('ix_audio_assets_narrator_user_id'), 'audio_assets', ['narrator_user_id'], unique=False)
    op.create_index(op.f('ix_audio_assets_status'), 'audio_assets', ['status'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('actor_user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mfa_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_auth_sessions_family_id'), 'auth_sessions', ['family_id'], unique=False)
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('listening_daily',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('seconds', sa.Float(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'day')
    )
    op.create_table('narrator_profiles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('languages', postgresql.ARRAY(sa.String(length=16)), server_default='{te-IN}', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('asset_rights',
    sa.Column('audio_asset_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='needs-review', nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=True),
    sa.Column('rights_holder', sa.Text(), nullable=True),
    sa.Column('recording_rights', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('performance_rights', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('adaptation_rights', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('artwork_rights', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('music_rights', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('territory', sa.Text(), nullable=True),
    sa.Column('allowed_uses', sa.Text(), nullable=True),
    sa.Column('license_start', sa.Date(), nullable=True),
    sa.Column('license_end', sa.Date(), nullable=True),
    sa.Column('evidence_reference', sa.Text(), nullable=True),
    sa.Column('attested_by', sa.Text(), nullable=True),
    sa.Column('attested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewer', sa.Text(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audio_asset_id'], ['audio_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('audio_asset_id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('audio_asset_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='queued', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='3', nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('leased_by', sa.String(length=64), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('log_tail', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audio_asset_id'], ['audio_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_jobs_asset_type', 'jobs', ['audio_asset_id', 'job_type'], unique=False)
    op.create_index('ix_jobs_ready', 'jobs', ['status', 'job_type', 'run_after'], unique=False)
    op.create_table('listener_favorites',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('audio_asset_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audio_asset_id'], ['audio_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'audio_asset_id')
    )
    op.create_table('listening_progress',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('audio_asset_id', sa.String(length=32), nullable=False),
    sa.Column('seconds_listened', sa.Float(), server_default='0', nullable=False),
    sa.Column('last_position', sa.Float(), server_default='0', nullable=False),
    sa.Column('play_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('first_listened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_listened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audio_asset_id'], ['audio_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'audio_asset_id')
    )
    op.create_table('narrator_credits',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('narrator_user_id', sa.BigInteger(), nullable=False),
    sa.Column('audio_asset_id', sa.String(length=32), nullable=False),
    sa.Column('awarded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reason', sa.Text(), server_default='approved publication', nullable=False),
    sa.ForeignKeyConstraint(['audio_asset_id'], ['audio_assets.id'], ),
    sa.ForeignKeyConstraint(['narrator_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audio_asset_id')
    )
    op.create_index(op.f('ix_narrator_credits_narrator_user_id'), 'narrator_credits', ['narrator_user_id'], unique=False)
    op.create_table('transcripts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('audio_asset_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('raw_key', sa.Text(), nullable=True),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('source_audio_checksum', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='needs-review', nullable=False),
    sa.Column('reviewer', sa.Text(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audio_asset_id'], ['audio_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audio_asset_id', 'version')
    )
    op.create_index(op.f('ix_transcripts_audio_asset_id'), 'transcripts', ['audio_asset_id'], unique=False)
    op.create_index(op.f('ix_transcripts_status'), 'transcripts', ['status'], unique=False)
    op.create_table('teaser_drafts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('audio_asset_id', sa.String(length=32), nullable=False),
    sa.Column('transcript_id', sa.BigInteger(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('short_text', sa.Text(), nullable=True),
    sa.Column('long_text', sa.Text(), nullable=True),
    sa.Column('alternates', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('themes', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('mood', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('age_suggestion', sa.Text(), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), server_default='needs-review', nullable=False),
    sa.Column('reviewer', sa.Text(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audio_asset_id'], ['audio_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teaser_drafts_audio_asset_id'), 'teaser_drafts', ['audio_asset_id'], unique=False)
    op.create_index(op.f('ix_teaser_drafts_status'), 'teaser_drafts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teaser_drafts_status'), table_name='teaser_drafts')
    op.drop_index(op.f('ix_teaser_drafts_audio_asset_id'), table_name='teaser_drafts')
    op.drop_table('teaser_drafts')
    op.drop_index(op.f('ix_transcripts_status'), table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_audio_asset_id'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index(op.f('ix_narrator_credits_narrator_user_id'), table_name='narrator_credits')
    op.drop_table('narrator_credits')
    op.drop_table('listening_progress')
    op.drop_table('listener_favorites')
    op.drop_index('ix_jobs_ready', table_name='jobs')
    op.drop_index('ix_jobs_asset_type', table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('asset_rights')
    op.drop_table('narrator_profiles')
    op.drop_table('listening_daily')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_family_id'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_audio_assets_status'), table_name='audio_assets')
    op.drop_index(op.f('ix_audio_assets_narrator_user_id'), table_name='audio_assets')
    op.drop_index(op.f('ix_audio_assets_language'), table_name='audio_assets')
    op.drop_index(op.f('ix_audio_assets_collection'), table_name='audio_assets')
    op.drop_table('audio_assets')
    op.drop_table('workers')
    op.drop_table('users')
    op.drop_index(op.f('ix_email_otps_email'), table_name='email_otps')
    op.drop_table('email_otps')
    op.drop_index('ix_editorial_events_entity', table_name='editorial_events')
    op.drop_table('editorial_events')
    # ### end Alembic commands ###
